# Generated by Django 4.2.5 on 2023-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("phone", models.CharField(max_length=10, verbose_name="Phone")),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                ("text", models.TextField(max_length=300, verbose_name="Comment")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(max_length=100, verbose_name="Client")),
                ("phone", models.CharField(max_length=10, verbose_name="Phone")),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                (
                    "order",
                    models.TextField(max_length=300, verbose_name="Order comment"),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Order Number"
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="order_files/",
                        verbose_name="File Upload",
                    ),
                ),
            ],
        ),
    ]
